### PR TITLE
1.19.4 Release for Orion

### PR DESCRIPTION
**Pull request by CrytoPal**
## Description

Makes Orion 1.19.4

## Motivation and Context

Because why not?

## How Has This Been Tested?

Used it with latest meteor dev

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [x] Have you successfully ran tests with your changes locally?
Just made the addon compatible with 1.19.4

### CODE REVIEW

**Comment by RacoonDog** [comment]
50F0017D-250D-4FE6-85E1-825B92A4A464
no. this is stupid

**Comment by CrytoPal** [comment]
Thing is, it works.

**Comment by tympanicblock61** [comment]
yeah no (int) 0.5 always returns 0

**Comment by tympanicblock61** [comment]
might as well just set it to 1 or remove it

**Comment by tympanicblock61** [comment]
image
this is incorrect also and you just cast everything to a int instead of actually fixing the vec3d issues

**Comment by tympanicblock61** [comment]
> 50F0017D-250D-4FE6-85E1-825B92A4A464 no. this is stupid

i agree

**Pull request closed without merging**
